### ISSUE TITLE
make_signed_coefficient_full(takatori::decimal::triple value) の結果が不正になるケースがある

### ISSUE THREAD

**Issue by t-horikawa** [project-tsurugi/jogasaki#100]
https://github.com/project-tsurugi/jogasaki/blob/9cc5fa7507e6eaf89e2ee7b58ed9261a66e9d668/src/jogasaki/utils/decimal.h#L38
に対するテスト（https://github.com/project-tsurugi/jogasaki/blob/9cc5fa7507e6eaf89e2ee7b58ed9261a66e9d668/test/jogasaki/utils/decimal_utils_test.cpp#L94）
の亜種として、
```
TEST_F(decimal_utils_test, negative_max_represented_by_9_bytes_variation) {
    auto [hi, lo, sz] = utils::make_signed_coefficient_full({-1, 0, 0x8000000000000001UL, 0});
    EXPECT_EQ(0xFFFFFFFFFFFFFFFFUL, hi);
    EXPECT_EQ(0x7FFFFFFFFFFFFFFFUL, lo);
    EXPECT_EQ(9, sz);
}
```
を追加すると、szが9ではなく8となるため、このテストはfailする（szは9となるのが正しいはず）。

**Comment by kuron99** [comment]
直近のコミットでテストケースを整理し、上記のテストケースは `negative_min_represented_by_8_bytes_minus_one` という名前に変更しました。

```
TEST_F(decimal_utils_test, negative_min_represented_by_8_bytes_minus_one) {
    auto [hi, lo, sz] = utils::make_signed_coefficient_full({-1, 0, 0x8000000000000001UL, 0});
    EXPECT_EQ(0xFFFFFFFFFFFFFFFFUL, hi);
    EXPECT_EQ(0x7FFFFFFFFFFFFFFFUL, lo);
    EXPECT_EQ(9, sz);
}
```

**Comment by kuron99** [comment]
2月末時点で修正済でした。クローズします。

**Comment by kuron99** [comment]
修正前のコードが引き起こしていた問題について追記します。

下記の2条件両方を満たす場合、ダンプの結果が本来の値と異なることがありました
- DECIMAL型の列を含む結果をファイルにダンプしている
- その列に含まれる値が負の値である

原因
扱うデータの長さの計算を誤っていたため、ファイルへダンプするときにDECIMALの負の数の一部が正しくデコーディングされず正の値になってしまった

再現方法
DECIMAL(38)型の列を持つテーブルに値-129を挿入し、ダンプしてファイルを確認すると127になっている。
```
tgsql> CREATE TABLE t (c0 DECIMAL(38) primary key);
tgsql> INSERT INTO t VALUES (CAST('-129' AS DECIMAL(*,*)));
tgsql> select * from t;
[c0: DECIMAL]
[-129]
(1 row)

$ ./tgdump -c ipc:tsurugi --to /tmp/dump t
table dump operation was started: table=t, output=/tmp/dump/t
table dump operation was finished: table=t, output=/tmp/dump/t

$ ./qv t/
+-----+
| c0  |
+-----+
| 127 |
+-----+
```
